name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v1
      - name: Install libxlsxwriter
        run: brew install libxlsxwriter
      - name: Build and test
        run: swift test
